#!/bin/sh
#
# CVS ID: GeotiffReader,v 1.3 2015/07/29 21:02:52 guym Exp
#
# Wrapper script to run the GeotiffReader java class's main method.
#

# Location of this script
BASE=`dirname $0`

if [ $# -eq 0 ]; then
   echo "Usage: $0 [--changekey OLD,NEW] <file>"
else
java -Djava.awt.headless=true \
     -cp $BASE/../..:${HiRISE_ROOT:=/HiRISE} \
     HiRISE.PDS_JP2.util.GeotiffReader $*
fi
